name: Quadrate Testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: |
          go mod tidy
          go build ./cmd/quadrated/

      - name: Testing x/tokenfactory/keeper
        run: go test -v github.com/QuadrateOrg/core/x/tokenfactory/keeper
      
      - name: Testing x/tokenfactory/types
        run: go test -v github.com/QuadrateOrg/core/x/tokenfactory/types

      - name: Testing x/erc20
        run: go test -v github.com/QuadrateOrg/core/x/erc20/keeper
